# 4. Dive into Python
<span id="chapters_ch4_dive_into_python_dive_into_python"> </span>
<span id="chapters_ch4_dive_into_python__doc"> </span>

After having covered some background on how a computer works (Chapter 1), how we
solve problems with computers (Chapter 2) and how we can represent data in binary (Chapter 3),
we are ready to interact with, learn to represent data, and perform actions in Python.

The Python interpreter that we introduced in  is a program waiting for our
computational demands if not executing something already. 
Those demands that describe an algorithm must be expressed in Python as a sequence
of “actions“ where each action can serve two broad purposes:
  * **Creating or modifying data**: These actions take in data, perform
*sequential*, *conditional*, or *repetitive* execution on the data, and
     produce other data. Computations that form the basis for our
     solutions are going to be performed with these kinds of actions.
     
  * **Interacting with the environment**: Our solutions will usually
     involve interacting with the user or the peripherals of the computer
     to take in (input) data or take out (output) data. This is achieved by using actions that enable interaction with the “environment“.
     
Regardless of its purpose, an action can be of two types:

  1.  **Expression**: An expression 
      (e.g., `3 + 4 * 5`) specifies a
      calculation which, when evaluated (performed), yields some data as a
      result. An expression can consist of:

      * *basic data* (integer, floating point, Boolean, etc.) or *container
          data* (e.g., string, list, set, etc.).
          
      * expressions involving operations among data and other expressions.
      * *function*s acting on expressions.     

  1. **Statement**: Unlike an expression, a statement does *not* return
     data as a result. It can either be basic or compound:

     * **Basic statement**: A basic statement can be, e.g., for storing the
          result of an expression in a memory location (an *assignment*
          statement for further use in subsequent actions), deleting an item
          from a collection of data, etc. Each statement has its special
          syntax that generally involves a special keyword.
          
     * **Compound statement**: Compound statements are composed of other
          statements, and control the execution of those statements in some way.
          
**Naming and Printing Data**

For the sake of clarity, we will make use of two concepts (variables and printing data) before they are introduced in more detail in the second part of the chapter. Let us briefly
describe them and leave the coverage of the details to their individual
sections:

  * **Variables**: In programming languages, we can give a name to data and
     use that name to access it, e.g.:  
     ```python
     >>> a = 3
     >>> 10 + a
     13
    ```
    Here, we asked Python to add 10 with a value referred to by the name `a`, and Python produced the result as `13`. We call such names  *variable*s, and the action `a = 3` is called an
    assignment. We defer a more detailed coverage until . 
     
  * **Printing data**: Python provides the `print()` function to display
     data items on the screen:  
     ```python
     print(item1, item2, ..., itemN)
     ```
    where `item` can be of any data type. For example:  
    ```python
     >>> print('Python', 'is', 'so', 'fun')
     Python is so fun
    ```

## 4.1 Basic Data
<span id="chapters_ch4_dive_into_python_basic_data"> </span>

The following are the basic data  types we frequently use:
  * Numbers
    * Integers      
    * Floating point numbers      
    * Complex numbers      
  * Booleans
     
In Python, arithmetic operations between numbers of the same type are provided in a way that is consistent with our mathematical expectations. Furthermore,
mixed-type operations (e.g., subtracting a floating point
number form an integer) are also possible.

In programming, being able to ask questions about data is vitally important.
The atomic structures for asking questions are the *comparison operations* (e.g., “is a value equal to another value”, or “is a
value greater than another value”, etc.).
Operators that serve these purposes do exist in Python and provide resulting values that are `True` or `False`(Booleans). It is also possible to combine such questions under *logical operations*. The `and`, `or` and `not` operators stand for conjunction, disjunction, and negation, correspondingly. Needless to say, these operators also return Boolean values `True` or `False`.

### 4.1.1 Numbers in Python
<span id="chapters_ch4_dive_into_python_numbers_in_python"> </span>

Python provides the following representations for numbers (the following
is an essential reminder from the previous chapter):
  * **Integers:** You can use integers as you are used to from your math
     classes. Interestingly, Python adopts a seamless internal
     representation so that integers can effectively have any number of
     digits. The internal mechanism of Python silently switches from the
     CPU-imposed fixed-size integers to some elaborated big-integer
     representation  when needed. You do not have to worry about
     it. Furthermore, keep in mind that “73.” is **not** an integer in
     Python. It is a floating point number (73.0). An integer cannot have
     a decimal point as part of it.
     
  * **Floating point numbers (float in short):** In Python, numbers that have a decimal point are taken and represented as floating point
     numbers. For example, 1.45, 0.26, and -99.0 are float but 102 and -8
     are not. We can also use the scientific notation
     ($a \times 10^b$) to write floating point numbers. For example,
     float 0.0000000436 can be written in scientific notation as $4.36 \times 10^{-8}$ and in Python as 4.36E-8 or 4.36e-8.
     
  * **Complex numbers:** In Python, complex numbers can be created by
     using `j` after a floating point number (or integer) to denote the
     imaginary part: e.g., `1.5-2.6j` for the complex number $(1.5-2.6i)$. The `j` symbol (or $i$) represents $\sqrt{-1}$. There are other ways to create complex numbers,
     but this is the most natural way, considering your previous knowledge
     from high school.
     
**More on Integers and Floating Point Numbers**
Python provides the `int` data type for integers and `float` data type
for floating-point numbers. You can easily play with the `int` and
`float` numbers and check their types as follows:
```python
>>> 3+4
7
>>> type(3+4)
<class 'int'>
>>> type(4.1+3.4)
<class 'float'>
```

where `<class 'int'>` indicates type `int`.

As we mentioned above, in Python version 3, integers do not have fixed-size representation, and
their size is only limited by your available memory. In Python version
2, there were two integer types: (i) `int`, which used the fixed-length two's complement
representation (covered in Chapter 3) supported by the CPU, and (ii) `long`, which was
unbounded. Since this book is based on Python version 3, we assume
that `int` refers to an unbounded representation.

As for the `float` type, Python uses the 64-bit IEEE 754 standard (covered in Chapter 3),
which can represent numbers in the range
`[2.2250738585072014E-308, 1.7976931348623157E+308]`.

**Useful Operations**:

The following functions can be useful when working with numbers:
  * `abs(<Number>)`: Takes the absolute value of the number.
```python
     >>> abs(-3.2)
     3.2
     >>> abs(3.2)
     3.2
```
  * `pow(<Number1>, <Number2>)`: Takes the power of `<Number1>`,
     i.e., $\textrm{<Number1>}^{\textrm{<Number2>}}$. Python also provides an operator (`**`) for taking the power of numbers: `<Number1> ** <Number2>`.
```python
     >>> pow(3, 2.4)
     13.966610165238235
     >>> pow(3, -1)
     0.3333333333333333
```
  * `round(<FloatNumber>)`: Rounds the floating point number to the
*closest* integer.
```python
     >>> round(4.2)
     4
     >>> round(4.6)
     5
```
  * Functions from the `math` library: `sqrt()`, `sin()`,
`cos()`, `log()`, etc (see [the Python
     documentation](https://docs.python.org/3/library/math.html) for a
     full list). This requires *importing* from the built-in `math` library
     first as follows:
```python
     >>> from math import *
     >>> sqrt(10)
     3.1622776601683795
     >>> log10(3.1622776601683795)
     0.5
```

### 4.1.2 Boolean Values
<span id="chapters_ch4_dive_into_python_boolean_values"> </span>

Python provides the `bool` data type which allows only two values:
`True` and `False`. For example:


```python
>>> type(True)
<class 'bool'>
>>> 3 < 4
True
>>> type(3 < 4)
<class 'bool'>
```

Python converts several
instances of other data types to Boolean values, if used in
a place where a Boolean value is expected. For example,
  * `0`(the integer zero)
     
  * `0.0`(the floating-point number zero)
     
  * `""`(the empty string)
     
  * `[]`(the empty list)
     
  * `{}`(the empty dictionary)
     

are interpreted as `False`. All other values are
interpreted as `True`.

**Useful Operations**:

With Boolean values, we can use the `not` (negation or inverse), `and`
and `or` operations:


```python
>>> True and False
False
>>> 3 > 4 or 4 < 3
False
>>> not(3 > 4)
True
```
`and` returns a `True` value only if both operands are
`True`, otherwise it returns `False`. `or` returns `True` if one
or both of its operands are `True`. The following table gives the result
of the Boolean operations for the given operand pair:


<table><tr><th> 
a
<th> 
b
<th> 
a <tt>and</tt> b
<th> 
a <tt>or</tt> b

<tr><td> 
<tt>True</tt></td>
<td>
<tt>True</tt></td>
<td>
<tt>True</tt></td>
<td>
<tt>True</tt></td>
</tr>
    
<tr><td> 
<tt>True</tt></td>
<td>
<tt>False</tt></td>
<td>
<tt>False</tt></td>
<td>
<tt>True</tt></td>
</tr>

<tr><td> 
<tt>False</tt></td>
<td>
<tt>True</tt></td>
<td>
<tt>False</tt></td>
<td>
<tt>True</tt></td>
</tr>

<tr><td> 
<tt>False</tt></td>
<td>
<tt>False</tt></td>
<td>
<tt>False</tt></td>
<td>
<tt>False</tt></td>
</tr>
</table>

## 4.2 Container Data (str, tuple, list, dict, set)
<span id="chapters_ch4_dive_into_python_container_data_str_tuple_list_dict_set"> </span>

Up to this point, we have seen the basic data types. They are certainly
needed in our computations, but many world problems for which we seek
computerized solutions need more elaborate data. Just to mention a few:
  * Vectors 
  * Matrices     
  * Ordered and unordered sets
  * Graphs 
  * Trees 

Vectors and matrices are used in almost all simulations/problems of the
physical world. Sets are used to keep any property information as well
as   equivalences. Graphs are necessary for many spatial
problems. Trees are vital for representing hierarchical relational
structures, action logics, and organizing data for a quick search.

Python provides five container types for these:

  1. **String (`str`):** A string can hold a sequence of characters or
     only a single character. A string cannot be modified after creation.

  1. **List (`list`):** A list can hold ordered sets of all data types
     in Python (including another list). The elements of a list can be modified
     after creation.

  1. **Tuple (`tuple`):** The tuple type is very similar to the list
     type, but the elements cannot be modified after creation (similar to
     strings).

  1. **Dictionary (`dict`):** A very efficient data type that implements a
     mapping from a set of numbers, Booleans, strings, and tuples to any
     set of data in Python. Dictionaries are easily modifiable and
     extendable. Querying the mapping of an element to the ‘target’ data
     is carried out in almost constant time (irrespective of how many elements
     the dictionary has). In Computer Science terms, a dictionary is called the *hash table* data structure.

  1. **Set (`set`):** The `set` type is equivalent to sets in
     mathematics. The order of the elements is undefined. *(We de-emphasize the use
     of **set**)*.

The first three, namely string, list, and tuple, are called *sequential
containers*. They consist of consecutive elements indexed by integer
values starting at 0. A dictionary is not sequential and element indexes are
arbitrary. For brevity, we will abbreviate sequential containers as
*s-containers*.

All these containers have external representations, which are used in
inputting and outputting them (with all their content). In the following, we will
walk through some examples to explain them.

**Mutability vs. Immutability**

Some container types are created as ‘frozen’. After creating them, you can
completely destroy them, but you cannot change or delete their individual
elements. This is called *immutability*. Strings and tuples are
immutable whereas lists, dictionaries, and sets are *mutable*. With a
mutable container, it is possible to add new elements and change or delete existing ones. As we will see throughout the book, mutable data types will make programming easier for us.



### 4.2.1 Accessing Elements in Sequential Containers
<span id="chapters_ch4_dive_into_python_accessing_elements_in_sequential_containers"> </span>

All containers except `set` reveal and provide access to their individual elements by an
*indexing* mechanism with brackets, as illustrated in <a href="#chapters_ch4_dive_into_python_id1">Fig. 4.1</a>. 

<figure>
<span id="chapters_ch4_dive_into_python_id1"> </span>

<center><img src="img/fig4-1.png" width="150pt"></center>

<figcaption>Figure 4.1: How elements of a container are accessed</figcaption>
</figure>

For the s-containers, the *index* is an ordinal number where counting
starts from zero. For dictionaries, the index is a Python data item from
the source (domain) set. A *negative index* (usable only on
s-containers) means that the (counting) value is relative to the
end. A negative index can be converted to a positive index by adding the length of the container to
the negative value. It is nothing but index obtained by adding the length of the container.
Below we have an s-container that has a length of $(n+1)$ (note that indexing starts at 0!):

<figure>
<span id="chapters_ch4_dive_into_python_fig_pn_indexing"> </span>

<center><img src="img/fig4-2.png" width="400pt"></center>

<figcaption>Figure 4.2: Positive and negative indexing of  an s-container. </figcaption>
</figure>

However, in the near future, you might have to take into account this: 

<center><img src="img/arraysstartart1.jpg" width="400pt"></center>

Observe that, when you add $(n+1)$ to the negative
index, you obtain the positive one.

**Slicing**
S-containers provide a rich mechanism, called *slicing*, that allows
accessing multiple elements at once. This mechanism allows us to 
define a start index and an end index and access the items that lie in between
(<a href="#chapters_ch4_dive_into_python_fig_slicing">Fig. 4.3</a>):
 
![](img/fig4-3.png):
 
  * The element at the start index is the first to be accessed. 
  * The end index is where accessing stops (the element at the end index
     is **not** accessed - that is, the end index is not inclusive).
     
  * It is also possible to optionally define an increment (a “jump“ amount)
     between the indexes. After the element at $\mathtt{[}start\mathtt{]}$ is accessed first, $\mathtt{[}start+increment\mathtt{]}$ is accessed next. This
     goes on until the accessed position is equal to or greater than the end
     index. For negative indexing, a negative increment has to work from
     the bigger index towards the lesser, so $(start\_index>end\_index)$ is expected.
     
Below, with the introduction of strings, we will have extensive examples
on slicing.

If the s-container is immutable (e.g., string and tuple containers) then
slicing creates a copy of the sliced data. Otherwise, i.e., if the
s-container is mutable (i.e., the `list` container), then slicing provides
direct access to the original elements and therefore, they can be
updated, which updates the original s-container.

### 4.2.2 Useful and Common Container Operations
<span id="chapters_ch4_dive_into_python_useful_operations_common_to_containers"> </span>

The following operations are common to all or a subset of containers:

1. *Number of elements*:  
   For all containers, `len()` is a built-in function that returns the
   count of elements in the container that is given as argument to it,
   e.g.:
   ```python
   >>> len("Five")
   4
   ```

2. *Concatenation*:  
   String, tuple, and list data types can be combined using the ‘+’ operation:
   ```python
   <Container1> + <Container2>
   ```
   where the containers need to be of the same type. For example:
   ```python
   >>> "Hell" + "o"
   'Hello'
   ```

3. *Repetition*:  
   String, tuple, and list data types can be repeated using
   the ‘*’ operation:
   ```python
   <Container1> * <Number>
   ```
   where the container is copied `<Number>` many times. For example:
   ```python
   >>> "Yes No " * 3
   'Yes No Yes No Yes No '
   ```
4. *Membership*:  
   All containers can be checked for whether they contain
   a certain item as an element using `in` and `not in` operations:
   ```python
   <item> in <Container>
   ```
   or
   ```python
   <item> not in <Container>
   ```
   Of course, the result is either `True` or `False`. For dictionaries, the `in` operator tests whether the element is present in the domain    set, while for other data structures, it checks if the element is a member.


### 4.2.3 String (str)
<span id="chapters_ch4_dive_into_python_string"> </span>

As explained in Section 3.5.2, a string is used to hold a
sequence of characters. Essentially, it is a container where each element
is a character. However, Python does not have a special representation
for a single character. Single characters, if necessary, are represented externally as strings
containing a single character only.

**Writing strings in Python**

In Python, a string is denoted by enclosing the character sequence
between a pair of quotes (`'Example String'`) or double quotes (`"Example String"`). A string
surrounded with triple double quotes (`"""Example String"""`)
allows you to have any combination of quotes and line breaks within a
sequence and Python will still view it as a single entity.

Here are some examples:
  * `"Hello World!"`
  * `'Hello World!'`
  * `'He said: "Hello World!" and walked towards the house.'`
  * `"A"`
  * `"""`  
    `Andrew said:`  
    `"Come here, doggy".`  
    `The dog barked in reply: 'woof'`  
    `"""`

The backslash (`\`) is a special character in Python strings, also
known as the *escape character*. It is used in representing certain, the
so-called, unprintable characters: `\t` is a tab, `\n` is a
newline, and `\r` is a carriage return. <a href="#chapters_ch4_dive_into_python_table_escape_chars">Table 4.1</a>
 provides the full list.


<table><caption> Table 4.1: The list of escape characters in Python.<span id="chapters_ch4_dive_into_python_id3"> </span>
<span id="chapters_ch4_dive_into_python_table_escape_chars"> </span> </caption>
<tr><td> 
Escape Sequence
<td> 
Meaning
<tr><td> 
<tt>\\</tt>
<td>
Backslash (<tt></tt>\)
<tr><td> 
<tt>\'</tt>
<td>
Single quote (<tt>'</tt>)
<tr><td> 
<tt>\"</tt>
<td>
Double quote (<tt>"</tt>)
<tr><td> 
<tt>\a</tt>
<td>
ASCII Bell (BEL)
<tr><td> 
<tt>\b</tt>
<td>
ASCII Backspace (BS)
<tr><td> 
<tt>\f</tt>
<td>
ASCII Formfeed (FF)
<tr><td> 
<tt>\n</tt>
<td>
ASCII Linefeed (LF)
<tr><td> 
<tt>\r</tt>
<td>
ASCII Carriage Return (CR)
<tr><td> 
<tt>\t</tt>
<td>
ASCII Horizontal Tab (TAB)
<tr><td> 
<tt>\v</tt>
<td>
ASCII Vertical Tab (VT)
<tr><td> 
<tt></tt>\ <i>ooo</i>
<td>
ASCII character with octal value <i>ooo</i>
<tr><td> 
<tt>\x</tt><i>hh</i>
<td>
ASCII character with hex value <i>hh</i>
<tr><td> 
<tt>\u</tt><i>hhhh</i>
<td>
UNICODE character with hex value <i>hhhh</i>
</table>

Conversely, prefixing a special character with (`\`) turns it into an
ordinary character. This is called *escaping*. For example, `\'` is
the single quote character. `'It\'s raining'` therefore is a valid
string and equivalent to `"It's raining"`. Likewise, `"` can be
escaped: `"\"hello\""` is a string that begins and ends with the
literal double quote character. Finally, `\` can be used to escape
itself: `\\` is the literal backslash character. For `'\nnn'`,
*nnn* is a number in base 8, for `'\xnn' `*nn* is a number in base 16
(including letters from `A` to `F` as digits for values 10 to 15).

In Python v3, all strings use the Unicode representation where all
international symbols can be used, e.g.:
```python
>>> a = "Fıstıkçı şahap"
>>> a
'Fıstıkçı şahap'
```
**Examples with strings**  

Let us look at some examples to see what strings are in Python and what
we can do with them:
```python
>>> "This is a string"
"This is a string"
>>> "This is a string"[0]
'T'
>>> s = "This is a string"
>>> print(s[0])
T
>>> print(s[0],s[1],s[8],s[14],s[15])
T h a n g
```

Since strings are immutable, an attempt to change a character in a string
will badly fail:
```python
>>> s = "This is a string"
>>> print(s)
This is a string
>>> s[2] = "u"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'str' object does not support item assignment
```

Bottom line: You cannot change a character in a created string.

Let us go through a sequence of examples. We encourage you to run the
following examples on the Web page of this chapter. Feel free to
change the text and rerun the examples.

In [21]:

my_beautiful_string  = "The quick brown fox jumps over the lazy dog"
print("THE STRING:", my_beautiful_string, len(my_beautiful_string), "CHARACTERS")


THE STRING: The quick brown fox jumps over the lazy dog 43 CHARACTERS


In [22]:

my_beautiful_string[0]


'T'

In [23]:

my_beautiful_string[4]


'q'

In [24]:

my_beautiful_string[0:4]


'The '

In [25]:

my_beautiful_string[:4]


'The '

In [26]:

my_beautiful_string[4:]


'quick brown fox jumps over the lazy dog'

In [27]:

my_beautiful_string[10:15]


'brown'

In [28]:

my_beautiful_string[:-5]


'The quick brown fox jumps over the laz'

In [29]:

my_beautiful_string[-8:-5]


'laz'

In [30]:

my_beautiful_string[:]


'The quick brown fox jumps over the lazy dog'

In [31]:

my_beautiful_string[0:15:2]


'Teqikbon'

Strings are used to represent textual information.
Common places where strings are used are:
  *  Textual communication in natural language with the user of the program.
  *  Understandable labeling of parts of data: City names, individual names, addresses, tags, labels, etc.
  *  Denotation needs in human-to-human interactions.
     
**Useful operations with strings**:

In the following, we go over some common operations with strings. After having introduced object-oriented programming, we will cover more useful operations in Section 7.3.
  *  String creation: In addition to using quotes for string creation, the
`str()` function can be used to create a string from its argument,
     e.g.:
```python
     >>> str(4)
     '4'
     >>> str(4.578)
     '4.578'
```
  *  Concatenation, repetition, and membership:
```python
     >>> 'Programming' + ' ' + 'with ' + 'Python is' + ' fun!'
     'Programming with Python is fun!'
     >>> 'really fun ' * 10
     'really fun really fun really fun really fun really fun really fun really fun really fun really fun really fun '
     >>> 'fun' in 'Python'
     False
     >>> 'on' in 'Python'
     True
```
  *  Evaluating a string: If you have a string that is an expression
     describing a computation, you can use the `eval()` function to
     evaluate the computation and get the result, e.g.:
```python
     >>> s = '3 + 4'
     >>> eval(s)
     7
```

**Deletion and insertion from/to strings**  
Since strings are immutable, modifying them directly is not possible. The only way to modify a string is by creating a new string, which involves utilizing slicing and concatenation operations (using “`+`“). The new string is then replaced in the same location as the former one. For example:
```python
>>> a = 'Python'
>>> a[0] = 'S'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'str' object does not support item assignment
>>> b = 'S' + a[1:]
>>> b
'Sython'
```

### 4.2.4 List and Tuple
<span id="chapters_ch4_dive_into_python_list_and_tuple"> </span>

Both list and tuple data types have a very similar structure on the
surface: They are sequential containers that can contain any other data
type (including other tuples or lists) as elements. The only difference
concerning the programmer is that tuples are immutable whereas lists are
mutable. As discussed at the beginning of <a href="#chapters_ch4_dive_into_python_container_data_str_tuple_list_dict_set">Section 4.2</a>, being immutable means that, after being
created, it is not possible to change, delete or insert any element in a
tuple.

Lists are created by enclosing elements into a pair of brackets and
separating them with commas, e.g., `["this", "is", "a", "list"]`.
Tuples are created by enclosing elements into a pair of parentheses,
e.g., `("this", "is", "a", "tuple")`. There is no restriction on the
elements: They can be any data (basic or container).

Let us look at some examples for lists:
  * `[9,3,1,-1,6]`
  * `[]`
  * `[2020]`
  * `[3.1415, 2.718281828]`
  * `[["pi,3.1415"], ["e",2.718281828], 1.41421356]`
  * `['the' 'quick','brown','fox','jumped','over','the','lazy','dog']`
  * `[10, [5, [3, [[30, [[30, [], []]], []]], []], [8, [], []]], [30, [], []]]`
  * `[[1,-1,0],[2,-3.5,1.1]]`
 
and some examples for tuples:
  * `('north','east','south','west')`
  * `()`
  * `('only',)`
  * `('A',65,"1000001","0x41")`
  * `("abx",[1.32,-5.12],-0.11)`

Of course, tuples can become list members as well, or vice versa:
  * `[("aerys","targaryen",("deceased", 1996)), ("brandon","stark","not born")]`
  * `(["aerys","targaryen",("deceased", 1996)], ["brandon","stark","not born"])`

Programmers generally prefer using lists over tuples since they allow
changing elements, which is often a useful facility in many problems.

Lists (and tuples) are used whenever there is a need for an ordered set.
Here are a few use cases for lists and tuples:
  * Vectors.
  * Matrices.
  * Graphs.
  * Board game states.
  * Student records, address books, or any inventory.
     
**Useful operations with lists and tuples**

In the following, we go over some common operations with lists and tuples. After having introduced object-oriented programming, we will cover more useful operations in Section 7.3.

  1. *Deletion from lists* 
     As far as deletion is concerned, you can use two methods for the time being:
     * Assigning an empty list to the slice that is going to be removed:  
       ```python
        >>> L = [111,222,333,444,555,666]
        >>> L[1:5] = []
        >>> print(L)
        [111, 666]
       ```  
     * Using the `del` statement on the slice that is going to be removed:  
       ```python
       >>> L = [111,222,333,444,555,666]
       >>> del L[1:5]
       >>> print(L)
       [111, 666]
       ```
  1. *Insertion into lists*  
     For insertion, you can use three methods:
     * Using assignment with a degenerate use of slicing:
       ```python
       >>> L = [111,222,333,444,555,666]
       >>> L[2:2] = [888,999]
       >>> print(L)
       [111, 222, 888, 999, 333, 444, 555, 666]
       ```
     * The second method can insert only one element at a time, and requires
       object-oriented programming features (i.e., *<data>*`.function(...)`), which will be covered in Chapter 7.
       ```python
       >>> L = [111,222,333,444,555,666]
       >>> L.insert(2, 999)
       >>> print(L)
       [111, 222, 999, 333, 444, 555, 666]
       ```
       where the `insert()` function takes two parameters: The first parameter
       is the index where the item will be inserted and the second parameter is
       the item to be inserted.
     
     * The third methods uses the `append()` function to insert an element
       only to the end or `extend()` to append more than one element to
       the end:
       ```python
       >>> L = [111,222,333,444,555]
       >>> L.append(666)
       >>> print(L)
       [111, 222, 333, 444, 555, 666]
       >>> L.extend([777, 888])
       [111, 222, 333, 444, 555, 666, 777, 888]
      ```
  1. *Data creation with `tuple()` and `list()` functions*:  
      Similar to
      other data types, the tuple and list data types provide two functions for
      creating data from other data types. An example is provided below, after the last item.

  1. *Concatenation and repetition with lists and tuples*: Similar to
     strings, “`+`“ and “`*`“ can be used respectively to concatenate two
     tuples/lists and to repeat a tuple/list many times. An example is provided below, after the last item.

  1. *Membership*: Similar to strings, `in` and `not in` operations
     can be used to check whether a tuple/list contains an element. An example is provided below, after the last item.

Here is an example that illustrates the last three items:
```python
>>> a = ([3] + [5])*4
>>> a.append([3, 5])
>>> print(a)
[3, 5, 3, 5, 3, 5, 3, 5, [3, 5]]
>>> a.extend([3, 5])
>>> print(a)
[3, 5, 3, 5, 3, 5, 3, 5, [3, 5], 3, 5]
>>> b = tuple(a)
>>> print(b)
(3, 5, 3, 5, 3, 5, 3, 5, [3, 5], 3, 5)
>>> [3, 5] not in b
False
>>> [5, 3] not in b
True             #  test for single element, not subsequence
```

As mentioned, the examples with some containers included two
types of constructs that were not covered yet: One is the use of
“functions“ on containers, e.g., the use of `len()`. With your high
school background, the use of functions should be easy to understand. 

The second construct is something new. It appears that we can use some functions
suffixed by a dot to a container (e.g., the `append` and `insert`
usages in the examples above). This construct is an internal function
call of a data structure called *object*. Containers are actually objects
and in addition to their data containment property, they also have some
defined action associations. These actions are named as *member
functions*, and called (applied) on that object (in our case the
container) by means of this dot notation:

$$
\bullet \cdot f(\Box) \quad \text{has the conceptual meaning of} \quad f(\bullet, \Box)
$$

Do not try this explicitly as it will not work. The equivalence is just
“conceptual“: The function receives the object internally, as a
“hidden“ argument. All these will be covered in detail in Chapter 7.
Till then, for the sake of completeness, from time to time, we will be referring
to this notation. For the time being, simply interpret the use of member functions based on the equivalence
depicted above.

**Example: Matrices as Nested Lists**  
In many real-world problems, we often end up with a set of values that
share certain semantics or functionality. We can benefit from representing
them in a regular grid structure that we call matrix:
$$
\begin{split}A = \begin{pmatrix}
a_{11} & a_{12} & \ldots & a_{1n} \\
a_{21} & a_{22} & \ldots & a_{2n} \\
\vdots & \ddots & & \vdots & \\
a_{m1} & a_{m2} & \ldots & a_{mn}
\end{pmatrix},\end{split}
$$
which has $n$ columns and $m$ rows. We generally shorten
this as $m\times n$ and say that matrix $A$ has size
$m\times n$. 

Solutions to many different problems can be formulated as a set (system) of equations that describe relations
among a set of variables. The following is a simple example:

$$
\begin{split}\begin{array}{ccc}
3x + 4y + z & = & 4,\\
-3x + 3y + 5 &  = & 3,\\
x + y + z & = &  0.\\
\end{array}\end{split}
$$

These equations can be represented with matrices as follows:

$$
\begin{split}\begin{pmatrix}
3 & 4 & 1 \\
-3 & 3 & 5 \\
1 & 1 & 1
\end{pmatrix}
\begin{pmatrix}
x \\
y \\
z
\end{pmatrix} =
\begin{pmatrix}
4 \\
3 \\
0
\end{pmatrix} .\end{split}
$$

This represents the system of equations above in terms of matrices and matrix
multiplication. It is okay if you are not familiar with matrix
multiplication – we will briefly introduce the concept and use it as an example in
the next chapter.

Writing a problem in a matrix form as we did above allows us to group
the related aspects of the problem together and focus on these groups
for solving a problem. In our example, we grouped the coefficients in a
matrix, which allows us to analyze and manipulate the matrix of coefficients (the first matrix in the multiplication equation) to check whether, for this system of equations, there is a
solution, whether the solution is unique or what the solution is. All
these are questions that are studied in *Linear Algebra* and beyond the
scope of our book.

Let us now explore how matrices can be represented in Python. A simple and effective approach that allows for modifying elements of the matrix later is by using nested lists, as shown below:


```python
>>> A = [[3, 4, 1],
... [-3, 3, 5],
... [1, 1, 1]]
>>> A
[[3, 4, 1], [-3, 3, 5], [1, 1, 1]]
```

Compare this list with the first matrix in the equation and note that each row is represented as a list which is a member of the outer list.
This would allow us to access entries like this:


```python
>>> A[1]  # 2nd row
[-3, 3, 5]
>>> A[1][0] # 2nd row, 1st element
-3
```

Although we can represent matrices like this, there are very advanced
libraries that make representing and working with matrices more
practical, as we will see in Chapter 10. For an extended coverage of matrices and matrix operations, we refer to the [Matrix algebra for beginners](http://vcp.med.harvard.edu/papers/matrices-1.pdf)  or Chapter 2 of [“Mathematics for Machine Learning”](https://mml-book.com).



### 4.2.5 Dictionary
<span id="chapters_ch4_dive_into_python_dictionary"> </span>

Dictionary is a container data type where accessing items can be
performed with indexes that are not numerical. In fact, in dictionaries,
indexes are called *keys*. A list, tuple, or string data type stores a
certain element at each numerical index (key). Similarly, a dictionary
stores an element (value) for each key. In other words, a dictionary is
just a mapping from keys to values (<a href="#chapters_ch4_dive_into_python_fig_dictionary">Fig. 4.4</a>).

The keys can only be immutable data types, i.e., numbers, strings, or
tuples (with only immutable elements); some other immutable types that
we do not cover in this book can also be used as keys. Since lists and
dictionaries are mutable, they cannot be used as keys for indexing. Regarding values, there is no limitation on the data type.

A dictionary is a “discrete“ mapping from a set of Python elements to
another set of Python elements. Dictionaries, as well as their individual
elements, are mutable (you can replace them). Moreover, it is possible
to add and remove items from the mapping.


<figure>
<span id="chapters_ch4_dive_into_python_id4"> </span>
<span id="chapters_ch4_dive_into_python_fig_dictionary"> </span>

<center><img src="img/fig4-4.png" width="600pt"></center>

<figcaption>Figure 4.4: A dictionary provides a mapping from keys to values</figcaption>
</figure>

A dictionary is represented as key-value pairs, each separated by a
column sign (`:`) and all enclosed in a pair of curly braces. The
dictionary in <a href="#chapters_ch4_dive_into_python_fig_dictionary">Fig. 4.4</a> would be denoted as:
```python
{49: "Germany",
44: "United Kingdom",
90: "Turkey",
"Istanbul": ["city", (41.0383,28.9703), "Where East meets West!", 34, 15.5e6],
("Charlize Theron", (0,13)): "South Africa",
"james bond": ["movie char", "007"],
"Barack Obama": ["president", "USA", (2009, 2017)],
("table", "leg"): [3, 4],
"casa": "home"}
```

Similar to other containers, we usually access dictionaries via 
variables. Let us assume the dictionary above was assigned to a variable
with the name `conno` and look at some examples:

In [32]:
conno = {49: "Germany", 44: "United Kingdom", 90: "Turkey", "Istanbul": ["city", (41.0383,28.9703), "Where East meets West!", 34, 15.5e6], ("Charlize Theron", (0,13)): "South Africa", "james bond": ["movie char", "007"], "Barack Obama": ["president", "USA", (2009, 2017)], ("table", "leg"): [3, 4], "casa": "home"}
print(conno["james bond"])
print(conno["Istanbul"])


['movie char', '007']
['city', (41.0383, 28.9703), 'Where East meets West!', 34, 15500000.0]



Let us ask for something that does not exist in the dictionary:



In [33]:
print(conno["london"])

KeyError: 'london'


Ups, that was bad! To avoid such a situation, we have a simple  method to test for the
existence of a key in a dictionary, by using the `in` operation:



In [ ]:
print("london" in conno)

False



It is also possible to remove/insert key-value pairs from/to a dictionary:



In [ ]:

print("conno has this many keys:", len(conno))
conno["london"] = ["capital", "london eye", 44]
print("conno has this many keys now:", len(conno))
print(conno["london"])
print(conno["james bond"])
del conno["james bond"]
print("james bond" in conno)
print("After 'james bond' is deleted we have this many keys:", len(conno))


conno has this many keys: 9
conno has this many keys now: 10
['capital', 'london eye', 44]
['movie char', '007']
False
After 'james bond' is deleted we have this many keys: 9



The benefit of using a dictionary is “time efficiency“. The functionality of a
dictionary could be attained by using (key, value) tuples inserted into
a list. In such a representation, when you need the value of a certain key, you can search
one-by-one each (key, value)-tuple element of the list until you find
your key in the first position of a tuple element. However, this will
consume time proportional to the length of the list (the worst case). On
the contrary, in a dictionary, this time is almost constant.

Moreover, a dictionary is more practical to use since it already
provides accessing elements in a key-based fashion.

**Useful Operations with Dictionaries**  
Dictionaries support `len()` and membership (`in` and `not in`)
operations that we have seen above. You can also use
`<dictionary>.values()` and `<dictionary>.keys()` to obtain lists of
values and keys respectively, as illustrated for the `conno` dictionary
introduced above:

```python
>>> conno.values()
dict_values(['Germany', 'United Kingdom', 'Turkey', ['city', (41.0383, 28.9703), 'Where East meets West!', 34, 15500000.0], 'South Africa', ['movie char', '007'], ['president', 'USA', (2009, 2017)], [3, 4], 'home'])
>>> conno.keys()
dict_keys([49, 44, 90, 'Istanbul', ('Charlize Theron', (0, 13)), 'james bond', 'Barack Obama', ('table', 'leg'), 'casa'])
>>> for key in conno.keys(): print(f"key: {key} => value: {conno[key]}")
key: 49 => value: Germany
key: 44 => value: United Kingdom
key: 90 => value: Turkey
key: Istanbul => value: ['city', (41.0383, 28.9703), 'Where East meets West!', 34, 15500000.0]
key: ('Charlize Theron', (0, 13)) => value: South Africa
key: james bond => value: ['movie char', '007']
key: Barack Obama => value: ['president', 'USA', (2009, 2017)]
key: ('table', 'leg') => value: [3, 4]
key: casa => value: home
```

### 4.2.6 Set
<span id="chapters_ch4_dive_into_python_set"> </span>
*Set*s are created by enclosing elements into a pair of curly braces and
separating them with commas. Any immutable data type, namely a number, a
string, or a tuple, can be an element of a set. Mutable data types
(lists, dictionaries) cannot be elements of a set. Since sets are mutable, 
sets themselves cannot be elements of other sets.

Here is a small example with sets:

In [ ]:

a = {1,2,3,4}
b = {4,3,4,1,2,1,1,1}
print (a == b)
a.add(9)
a.remove(1)
print(a)



True
{2, 3, 4, 9}



Lists can undertake most functionalities of sets.
Furthermore, lists do not possess the restrictions that sets do. On the other
hand, membership tests especially are much faster with sets, since
member repetition is avoided.

**Frozenset**  
Python provides an immutable version of the set type, called
`frozenset`. A `frozenset` can be constructed using the
`frozenset()` function as follows:

```python
>>> s = frozenset({1, 2, 3})
>>> print(s)
frozenset({1, 2, 3})
```
Being immutable, frozensets can be a member of a `set` or a `frozenset`.

**Useful Operations with Sets**  
Apart from the common container operations (`len()`, `in` and
`not in`), sets and frozensets support the following operators:
  * `S1 <= S2`: `True` if `S1` is a subset of `S2`.
  * `S1 >= S2`: `True` if `S1` is a superset of `S2`.
  * `S1 | S2`: Union of the sets (equivalent to `S1.union(S2)`).
  * `S1 & S2`: Intersection of the sets (equivalent to
`S1.intersection(S2)`).
  * `S1 - S2`: Set difference (equivalent to `S1.difference(S2)`).
     

Here are some examples:


```python
>>> odd = {1, 3, 5, 7}
>>> even = {0, 2, 4, 6, 8}
>>> odd
{1, 3, 5, 7}
>>> even
{0, 2, 4, 6, 8}
>>> odd_and_even = odd | even
>>> odd_and_even
{0, 1, 2, 3, 4, 5, 6, 7, 8}
>>> odd <= odd_and_even # odd is a subset of odd_and_even?
True
>>> odd <= even # odd is a subset of even?
False
>>> odd_and_even - odd == even # (odd_and_even \ odd) =? even
True
```

The followings are only applicable with sets (and not with forezensets)
as they require a mutable container:
  * `S.add(element)`: Add a new element to the set.
     
  * `S.remove(element)`: Remove the element from the set.
     
  * `S.pop()`: Remove an arbitrary element from the set.
     

## 4.3 Expressions
<span id="chapters_ch4_dive_into_python_expressions"> </span>

Expressions such as `3 + 4` describe the calculation of an operation among
data. When an expression is *evaluated*, the operations in the
expression are applied to the data specified in the expression and a
resulting value is provided.

Operations can be graphically illustrated as follows:
$$
\begin{split}\Box_1 \odot \Box_2\end{split}
$$
where $\odot$ is called the operator, and $\Box_1$ and
$\Box_2$ are called the operands. In this example, the operator is binary, i.e., it
acts on two operands.

We can also have *unary* operators:
$$
\begin{split}\odot \Box\end{split}
$$
or operators that have more than two operands.

Before we can cover how such operations are evaluated, let us look at
the commonly used operations (operators) in Python.



### 4.3.1 Arithmetic, Logic, Container and Comparison Operations
<span id="chapters_ch4_dive_into_python_arithmetic_logic_container_and_comparison_operations"> </span>

Python provides various operators  for
*arithmetic* (addition, subtraction, multiplication, division,
exponentiation), logic (and, or, not), container (indexing, membership)
and *comparison* (less, less-than, equality, not-equality, greater,
greater-than) operations. Some operators might be applied to different container data types with different meanings. An operator compatibility matrix is given in  with their semantics (for Python 3.9). Note that Python is an evolving language and the operator compatibility in  may change from version to version, especially with major versions.

<table><caption> Table 4.2: Python operators and valid operand types are marked with a circle, ⏺. An empty cell means the data type is not supported by the operator.<span id="chapters_ch4_dive_into_python_tbl_operators"> </span></caption>
<tr><td>
      <td>  <tt>bool</tt>   <td>  <tt>int</tt>     <td>  <tt>float</tt>   <td>  <tt>str</tt>     <td>  <tt>list</tt>    <td>  <tt>tuple</tt>   <td>  <tt>dict</tt>    <td>  <tt>set</tt>    
<tr><td>  
<tt>+</tt><td>  ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td>⏺<sup>1</sup>    <td> ⏺<sup>2</sup>     <td> ⏺<sup>2</sup>     <td>⏺<sup>2</sup>     <td>   <td>     
<tr><td>  
<tt>-</tt><td>   ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td>   <td>   <td>   <td>   <td> ⏺<sup>8</sup>      
<tr><td>  
<tt>*</tt><td>   ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>3</sup>     <td> ⏺<sup>3</sup>     <td> ⏺<sup>3</sup>     <td>   <td>     
<tr><td>  
<tt>/</tt><td>   ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td>   <td>   <td>   <td>   <td>     
<tr><td>  
<tt>//</tt><td>  ⏺<sup>4</sup>     <td> ⏺<sup>4</sup>     <td> ⏺<sup>4</sup>     <td>   <td>   <td>   <td>   <td>     
<tr><td>  
<tt>%</tt><td>   ⏺<sup>5</sup>   <td> ⏺<sup>5</sup>  <td> ⏺<sup>5</sup> <td> ⏺<sup>6</sup>  <td>   <td>   <td>   <td>  
    <tr><td>
<tt><b>**</b></tt><td>  ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td>   <td>   <td>   <td>   <td>     
<tr><td>  
<tt>==</tt><td>  ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>7</sup>      <td> ⏺<sup>7</sup>      <td> ⏺<sup>7</sup>      <td> ⏺<sup>7</sup>      <td> ⏺<sup>7</sup>      
<tr><td>  
<tt><</tt><td>   ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>9</sup>    <td> ⏺<sup>9</sup>    <td> ⏺<sup>9</sup>    <td>   <td> ⏺<sup>8</sup>      
<tr><td>  
<tt>></tt><td>   ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>9</sup>    <td> ⏺<sup>9</sup>    <td> ⏺<sup>9</sup>    <td>   <td> ⏺<sup>8</sup>      
<tr><td>  
<tt><=</tt><td>  ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>9</sup>    <td> ⏺<sup>9</sup>    <td> ⏺<sup>9</sup>    <td>   <td> ⏺<sup>8</sup>      
<tr><td>  
<tt>>=</tt><td>  ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>9</sup>    <td> ⏺<sup>9</sup>    <td> ⏺<sup>9</sup>    <td>   <td> ⏺<sup>8</sup>      
<tr><td>  
<tt>!=</tt><td>  ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>1</sup>    <td> ⏺<sup>7</sup>      <td> ⏺<sup>7</sup>      <td> ⏺<sup>7</sup>      <td> ⏺<sup>7</sup>      <td> ⏺<sup>7</sup>      
<tr><td>  
<tt>in</tt><td>    <td>   <td>   <td> ⏺<sup>10</sup>   <td> ⏺<sup>10</sup>   <td> ⏺<sup>10</sup>   <td> ⏺<sup>10</sup>   <td> ⏺<sup>10</sup>   
<tr><td>  
<tt>[]</tt>`<td>    <td>   <td>   <td> ⏺<sup>11</sup>   <td> ⏺<sup>11</sup>   <td> ⏺<sup>11</sup>   <td> ⏺<sup>12</sup>  <td>     
<tr><td>  
<tt>&</tt><td>   ⏺<sup>13</sup>    <td> ⏺<sup>13</sup>    <td>   <td>   <td>   <td>   <td>   <td> ⏺<sup>8</sup>     
<tr><td>  
<tt>|</tt><td>   ⏺<sup>13</sup>    <td> ⏺<sup>13</sup>    <td>   <td>   <td>   <td>   <td> ⏺<sup>8</sup>      <td> ⏺<sup>8</sup>    
<tr><td>  
<tt>^</tt><td>   ⏺<sup>13</sup>    <td> ⏺<sup>13</sup>    <td>   <td>   <td>   <td>   <td>   <td> ⏺<sup>8</sup>    
<tr><td>  
<tt>~</tt><td>   ⏺<sup>13</sup>    <td> ⏺<sup>13</sup>    <td>   <td>   <td>   <td>   <td>   <td>     
<tr><td>  
<tt>>></tt><td>  ⏺<sup>13</sup>    <td> ⏺<sup>13</sup>    <td>   <td>   <td>   <td>   <td>   <td>     
<tr><td>  
<tt><<</tt><td>  ⏺<sup>13</sup>    <td> ⏺<sup>13</sup>    <td>   <td>   <td>   <td>   <td>   <td>     
<tr><td>  
</table>
  
   1. Arithmetic operator with the default meaning. bool values are mapped to integers 0 and 1. Comparison operators return bool. Others return int if both operands are int, otherwise return float.  
  
   2. Concatenates two containers of the same type and returns the new container with the same type.  
  
   3. Repeats the elements of the container a given number of times to return a new container. The right operand should be an integer.  
  
   4. Integer part of the division. Returns int for int operands, float otherwise.  
  
   5. Remainder of the integer division. Returns int for int operands, float otherwise.  
  
   6. First operand is the format string. Returns the formatted string with the values from the right operand.  
  
   7. Equality of containers with the same data type. Element by element comparison. Returns bool.  
  
   8. Set operation, returns set. Comparison operators are mapped to subset ($\subset$) relation and return bool.  
  
   9. Lexicographic or dictionary order. The result depends on the leftmost differing element. Returns bool.   
  
   10. If the container contains the value provided as the right operand. For dictionaries, it searches the value in the keys only. Returns bool.  
  
   11. Member selection with an integer index. Slicing ([str:stp:inc] syntax) is supported. May return any type.  
  
   12. Member selection with an immutable index type. No slicing. May return any type.  
  
   13. Bitwise logical operation applied on bit by bit basis for integer types. Returns int.  

Below are some illustrative examples:



In [2]:
print("[1,2,3] + [3,4] -> ", [1,2,3] + [3,4])
print("(1,2,3) + (3,4) -> ", (1,2,3) + (3,4))
print("[1,2] * 3 -> ", (1,2) * 3)
print("'hello' * 3 -> ", 'hello' * 3)
S1 = "Four"
S2 = "Five"
print("len(S1) < len(S2) -> ", len(S1) < len(S2) )
print("S1 != S2  -> ", S1 != S2 )
print("S1 > S2  -> ", S1 > S2 )
print("[1,2,3] == [1,2,3] -> ", [1,2,3] == [1,2,3]) 
print("[1,2,3] == (1,2,3) -> ", [1,2,3] == (1,2,3)) 
print("[1,2,3] < [1,2,5] -> ", [1,2,3] <[1,2,5]) 
print("{1,2,3} < {1,2,5} -> ", {1,2,3} < {1,2,5}) 
print("{1,2} < {1,2,5} -> ", {1,2} < {1,2,5}) 
print("4 in [1,2,3,4] -> ", 4 in [1,2,3,4])
print("'i' in 'team'  -> ", 'i' in 'team')
print("4 in {4:'a', 5:'b'} -> ", 4 in {4: 'a', 5:'b'}) 
print("'a' in {4:'a', 5:'b'} -> ", 'a' in {4: 'a', 5:'b'}) 

[1,2,3] + [3,4] ->  [1, 2, 3, 3, 4]
(1,2,3) + (3,4) ->  (1, 2, 3, 3, 4)
[1,2] * 3 ->  (1, 2, 1, 2, 1, 2)
'hello' * 3 ->  hellohellohello
len(S1) < len(S2) ->  False
S1 != S2  ->  True
S1 > S2  ->  True
[1,2,3] == [1,2,3] ->  True
[1,2,3] == (1,2,3) ->  False
[1,2,3] < [1,2,5] ->  True
{1,2,3} < {1,2,5} ->  False
{1,2} < {1,2,5} ->  True
4 in [1,2,3,4] ->  True
'i' in 'team'  ->  False
4 in {4:'a', 5:'b'} ->  True
'a' in {4:'a', 5:'b'} ->  False


### 4.3.2 Bitwise Operators
*Bitwise* operators are logical operators defined for the integer data
type. In contrast to the bool type, bitwise logical operations are carried out in bit by bit manner. Each bit of the two’s complement representation of an integer value takes part in a logical operation with the same bit position of the other operand. `&` denotes the logical `and`, `|` denotes the logical `or`, and unary operator `~` denotes the logical `not`. Exclusive or, `^` has no Boolean counterpart. It gives 0 for the case where both values are the same, 1 otherwise. In addition to the binary logical operators, there are *left shift* (`<<`) and *right shift* (`>>`) operators that shift all bits to the left or right and pad 0 for the missing values. The right operand for a shift operator is an integer denoting how many times the bits will be shifted.

Bitwise operators are used in limited areas of programming like “cryptography“, “low-level I/O“, and hardware control. The following examples show how these operators work:

In [1]:
a = 85
b = 15
print('a:     ', '{:8b}'.format(a), a)
print('b:     ', '{:8b}'.format(b), b)
print('a & b: ', '{:8b}'.format(a & b), a & b )
print('a | b: ', '{:8b}'.format(a | b), a | b )
print('a ^ b: ', '{:8b}'.format(a ^ b), a ^ b )
print('a >> 3:', '{:8b}'.format(a >> 3), a >> 3 )
print('a << 3:', '{:8b}'.format(a << 3), a << 3 )

a:       1010101 85
b:          1111 15
a & b:       101 5
a | b:   1011111 95
a ^ b:   1011010 90
a >> 3:     1010 10
a << 3: 1010101000 680


### 4.3.3 Evaluating Expressions
<span id="chapters_ch4_dive_into_python_evaluating_expressions"> </span>

In the previous section, we have seen simple uses of operators in 
expressions. In many cases, we combine several operators for brevity and
readability, e.g. `2.3 + 3.4 * 4.5`. This expression can be evaluated
in two different ways:
  * `(2.3 + 3.4) * 4.5`, which would yield 25.65.
     
  * `2.3 + (3.4 * 4.5)`, which would yield 17.599999999999998 in
     Python.
     

Since the results are very different, it is very important for a
programmer to know in which order operators are evaluated when they are
combined. There are two rules that govern this:
  1. Precedence: Each operator has an associated precedence (priority)
     based on which we can determine the first operator to be
     evaluated. For example, multiplication has higher precedence than
     addition, and therefore, `2.3 + 3.4 * 4.5` would be evaluated as
`2.3 + (3.4 * 4.5)` in Python.

  1. Associativity: If two operators have the same precedence, the evaluation
     order is determined based on associativity. Associativity can be from
     left to right or from right to left.

For the operators, the complete associativity and precedence information
are listed in <a href="#chapters_ch4_dive_into_python_tbl_precedence_associativity">Table 4.3</a>.

<table><caption>Table 4.3: Precedence and associativity for the operators in <a href="#chapters_ch4_dive_into_python_tbl_operators">Table 4.2</a>
<span id="chapters_ch4_dive_into_python_id6"> </span>
<span id="chapters_ch4_dive_into_python_tbl_precedence_associativity"> </span>
</caption><tr><th>
Operator
<th> 
Precedence
<th> 
Associativity
<tr><td> 
<tt>[]</tt>
<td> 1. <td>
Left-to-right
<tr><td> 
<tt><b>**</b></tt>
<td> 2. <td>
Right-to-left
<tr><td> 
<tt>*</tt>, <tt>/</tt>, <tt>//</tt>,
<tt>%</tt>
<td> 3. <td>
Left-to-right
<tr><td> 
<tt>+</tt>, <tt>-</tt>
<td> 4. <td>
Left-to-right
<tr><td> 
<tt><</tt>, <tt><=</tt>, <tt>></tt>,
<tt>>=</tt>, <tt>==</tt>, <tt>!=</tt>,
<tt>in</tt>, <tt>not in</tt>
<td> 5. <td>
Left-to-right &amp; Special
<tr><td> 
<tt>not</tt>
<td> 6. <td>
Unary
<tr><td> 
<tt>and</tt>
<td> 7. <td>
Left-to-right
(with short-cut)
<tr><td> 
<tt>or</tt>
<td> 8. <td>
Left-to-right
(with short-cut)
<tr><td> 
</table>

Therefore, according to <a href="#chapters_ch4_dive_into_python_tbl_precedence_associativity">Table 4.3</a>, a
sophisticated expression such as `2**3**4*5-2//2-1` is equivalent to
`2**81*5-1-1` which is equivalent to
`12089258196146291747061760-2` which
is `12089258196146291747061758`.

Below are some notes and explanations regarding expression evaluation:

  1. The *Special* keyword in
<a href="#chapters_ch4_dive_into_python_tbl_precedence_associativity">Table 4.3</a> refers to a treatment which is common to mathematics but not to programming. Python is unique among commonly-used programming languages.
     If $\odot_i$ is any Boolean comparison operator and $\Box_j$ is any numerical expression, the sequence of
$$
     \begin{split}\Box_1 \odot_{\scriptsize\mathsf 1} \Box_2 \odot_{\scriptsize\mathsf 2} \Box_3 \odot_{\scriptsize\mathsf 3} \Box_4 \cdots \Box_{n-1} \odot_{n-\scriptsize\mathsf 1} \Box_n\end{split}
$$
     is interpreted as:
$$
     \begin{split}   \Box_1 \odot_{\scriptsize\mathsf 1} \Box_2 \;\;\mathtt{and}\;\;\; \Box_2 \odot_{\scriptsize\mathsf 2} \Box_3\;\;  \mathtt{and} \;\;\; \Box_3 \odot_{\scriptsize\mathsf 3} \Box_4 \;\;\;\cdots \;\;\; \Box_{n-1}
     \odot_{n-\scriptsize\mathsf 1} \Box_n\end{split}
$$
  1. It is **always** possible to override the precedence by making use of parentheses. This is precisely how we grouped calculations in our middle-school math courses. For example, for an expression such as $3+4*5$, if we want the addition to be performed first, we can use parentheses like $(3+4)*5$.

  1. If two numeric operands are of the same type, then the result is of that type unless the operator is `/`(for which the result is always a
     floating-point number). Also, comparison operators return `bool`
     typed values.

  1.  If two numeric operands that enter an operation are of different types (e.g., as in 3 + 4.5), then the operation is performed according to the following rules (see also <a href="#chapters_ch4_dive_into_python_implicit_and_explicit_type_conversion">Section 4.3.5</a>):
     
      * **If one operand is an integer and the other is a floating-point number:**  
       The integer is converted to floating point.
          
      * **If one operand is complex:** Complex arithmetic is performed according to the rules of mathematics among the coefficients of the real/imaginary parts (which are integers or floating points).
          Each of the two resulting coefficients is separately checked for having zero fractional part (.0).
          If so, then that one is converted to an integer.
          
  1. Except for
     the  logical operators `and` and `or`, all operators have an evaluation scheme that is coined as *eager evaluation*.
     Eager evaluation is the strategy where all operands are evaluated first and then the semantics of the operators kick in, providing the result.
     Here is an example: Consider the mathematical expression
     "`0*(2**150-3**95)`". 
     As intelligent beings, our immediate reaction would be as follows:
     Anything multiplied with `0`(zero) is `0`, therefore, we do not have to compute the two huge exponentiation operations within the parentheses.
     This is 
     taking a *short-cut* in evaluation and is certainly **far from** eager evaluation.
     Eager evaluation would evaluate the operations within the parentheses, obtain the value `- 693647454339354238433323618063349607247325483` and then multiply this with `0` to obtain `0`.
     Python would follow this “less intelligent“ way and perform eager evaluation.
     The logical operators `and` and `or`, though, **do not** adopt eager evaluation.
     On
     the contrary, they use *short-cuts* (this is known as *based-on-need evaluation* in computer science).
     For a conjunctive expression like:
     $$
     \begin{split}\Box_1 \;\;\mathtt{and}\;\;\; \Box_2  \;\;\mathtt{and}\;\;\; \Box_3 \;\;\mathtt{and}\;\;\; \cdots \;\;\mathtt{and}\;\;\; \Box_n\end{split}
     $$
     The evaluation proceeds as illustrated in <a href="#chapters_ch4_dive_into_python_id7">Fig. 4.5</a>.
     
<figure><span id="chapters_ch4_dive_into_python_id7"> </span>

<center><img src="img/fig4-5.png" width="350pt"></center>

<figcaption>Figure 4.5: Logical AND evaluation scheme</figcaption>
</figure>
     Similarly, a disjunctive expression:  

$$
\begin{split}\Box_1 \;\;\mathtt{or}\;\;\; \Box_2  \;\;\mathtt{or}\;\;\; \Box_3 \;\;\mathtt{or}\;\;\; \cdots \;\;\mathtt{or}\;\;\; \Box_n\end{split}
$$  

      has the evaluation scheme in <a href="#chapters_ch4_dive_into_python_id8">Fig. 4.6</a>.
      
<figure>
<span id="chapters_ch4_dive_into_python_id8"> </span>
     
<center><img src="img/fig4-6.png" width="350pt"></center>

<figcaption>Figure 4.6: Logical OR evaluation scheme</figcaption>
</figure>

Although high-level languages provide mechanisms for evaluating
expressions involving multiple operators, it is not a good programming
practice to leave multiple operators without parentheses. A programmer
should do his/her best to write code that (i) is readable and understandable
by other programmers and (ii) does not include any ambiguity.



### 4.3.4 Implicit and Explicit Type Conversion (Casting)
<span id="chapters_ch4_dive_into_python_implicit_and_explicit_type_conversion"> </span>

In Python, when you apply a binary operator on items of two different
data types, it tries to convert one data type to another data type if possible.
This is called *implicit type conversion*. For example,
```python
>>> 3+4.5
7.5
>>> 3 + True
4
>>> 3 + False
3
```

illustrates that an integer is converted to a float, `True` is
converted to the integer 1, and `False` is converted to the integer zero.

Although Python can do such conversions, it is a good programming
practice to make these conversions explicit to ensure the clarity of the intention
to the reader. Explicit type conversion, also called *type casting*,
can be performed using the keyword for the target type as a function.
For example:
```python
>>> 1.1*(7.1+int(2.5*5))
21.01
```

Not all conversions are possible. Implicit conversions are
allowed only for the basic data types as illustrated in <a href="#chapters_ch4_dive_into_python_id9">Fig. 4.7</a>:


<figure>
<span id="chapters_ch4_dive_into_python_id9"> </span>

<center><img src="attachment:.__chapter4__ch4_typecasting.png" width="170pt"></center>

<figcaption>Figure 4.7: Type casting among numeric and boolean types.</figcaption>
</figure>

Type conversion can accommodate conversion between a wider spectrum of data
types, including containers:
```python
>>> str(34)
'34'
>>> list('34')
['3', '4']
```

## 4.4 Basic Statements
<span id="chapters_ch4_dive_into_python_basic_statements"> </span>

Now, let us continue with actions that do not provide (return) us data
as a result.



### 4.4.1 Assignment Statement and Variables
<span id="chapters_ch4_dive_into_python_assignment_statement_and_variables"> </span>

After obtaining a result in Python, we often print and/or
keep the result for further computations.
*Variables* help us here as named memory positions in which we can store
data. You can imagine variables as pigeonholes that can hold 
**single** data items.

There are two methods to create and store data into a variable.
Here, we will mention the one that is overwhelmingly used. The other is more
implicit and will be introduced when we cover functions.

A variable receives data for storage using the *assignment
statement*. It has the following form:

$\boxed{\color{red}{Variable}} = \boxed{\color{red}{Expression}}$

Although the equal sign resembles an operator that is placed between two
operands, it is not an operator: Operators return a value, and in
Python, the assignment is not an operator and it does not return a value
(this can be different in other programming languages).

The action semantics of the assignment statement is simple:
  1. The $\color{red}{Expression}$ is evaluated.

  1. If the $\color{red}{Variable}$ does not exist, it is created.

  1. The evaluation result is stored into the $\color{red}{Variable}$ (by doing so, any prior value, if
     there is one, is purged).

After the assignment, the value can be used repetitively. To use the value in a computation, we can use the name of the variable. Here is an
example:
```python
>>> a = 3
>>> b = a + 1
>>> (a-b+b**2)/2
7.5
```

It is quite common to use a variable on both sides of the assignment
statement. For example:
```python
>>> a = 3
>>> b = a + 1
>>> a = a + 1
>>> (a-b+b**2)/2
8.0
```

The expression in the second line uses the integer `3` for `a`. In the
next line, namely, the third line, again `3` is used for `a` in the
expression (`a+1`). Then, the result of the evaluation `(3+1)`, which
is `4`, is stored in the variable `a`. The variable `a` had a
previous value of `3`; this value is purged and replaced by `4`. The
former value is not kept anywhere and cannot be recovered.

**Multiple assignments**  
Multiple variables can be assigned to the same value at once. For example,
```python
>>> a = b = 4
```

assigns an integer value of `4` to both `a` and `b`. After the
multi-assignment above, if you change `b` to some other value, the
value of `a` will still remain at `4`.

**Multiple assignments with different values**  
Python provides a powerful mechanism for providing different values to different variables in
assignment:
```python
>>> a, b = 3, 4
>>> a
3
>>> b
4
```

This is internally handled by Python with tuples and is equivalent to:
```python
>>> (a,b) = (3, 4)
>>> a
3
>>> b
4
```

This is called *tuple matching* and would also work with lists
(i.e., `[a, b] = [3, 4]`).

**Swapping values of variables**  
Tuple matching has a very practical
benefit: Let us say that you want to swap the values of two variables. Normally,
this requires the use of a temporary variable:
```python
>>> print(a,b)
3 4
>>> temp = a
>>> a = b
>>> b = temp
>>> print(a,b)
4 3
```

With tuple matching, we can do this in one line:
```python
>>> print(a,b)
3 4
>>> a,b = b,a
>>> print(a,b)
4 3
```
**Frequently-asked questions about assignments**  
  * **QUESTION:** Considering the example below, one may have doubts
     about the value of variable `b`: Is it updated? On the fourth line, there is
     an expression using the variable `b`: Which value is it referring to? `4` or `5`? When we use the variable `b` in a following expression, will the
     “definition“ be retrieved and recalculated?
     ```python
     >>> a = 3
     >>> b = a + 1
     >>> a = a + 1
     >>> (a-b+b**2)/2
     8.0
    ```
  * **ANSWER:** *No. Statements are executed only once here, when they
     are entered into the Python interpreter (it is possible to repetitively execute a statement but that is not the case in this example). Each assignment in the example above is
     executed only once. No re-evaluation is performed, the use of a
     variable in an expression, the “`a`” and those “`b`”s, refer
     solely to the last calculated and stored values: In the evaluation of
     “`(a-b+b**2)/2`”, “`a`” is 4, and “`b`” is 4*.
    
  * **QUESTION:** We had variables in math, especially in middle school
     and high school. This is very similar to that, right? But I am
     confused having seen a line like `a = a + 1`. What is happening? The
`“a”`s cancel out and we are left with `0 = 1`?
     
  * **ANSWER:** *The use of the equal sign (`=`) is confusing to some
     extent. It does not stand for a balance between the left-hand side and
     the right-hand side. Do not interpret it as an ‘equality’ in
     mathematics. It has absolutely different semantics. As discussed above, it
     only means:*
       1. **First** *calculate the right-hand side*,

       1. **Then** *store the result into an (electronic) pigeon hole which
          has the name label given to the left-hand side of the equal sign*.

  * **QUESTION:** I typed the following lines:
      ```python
        >>> x = 5
        >>> y = 3
        >>> x = y
        >>> y = x
        >>> print (x,y)
        3 3
      ```
     However, it should have been `3 5`, right? Or am I doing something
     wrong?
     
  * **ANSWER:** *You might be missing the time flow. The statements are
     executed in the following order:*
    
       1. **First:** *“`x`” is set to 5.*
       1. **Second:** *“`y`” is set to 3.*
       1. **Third:** *“`x`” is set to the value stored in “`y`” which is 3.
          “x” now holds 3.*
       1. **Fourth:** *“`y`” is set to the value stored in “`x`” which is 3
          (owing to the third step). “`y`” now
          holds 3.*
       1. **Fifth:** *print both the values in “`x`” and “`y`”. Both are “3”, as displayed on screen.*

### 4.4.2 Variables & Aliasing
<span id="chapters_ch4_dive_into_python_variables_aliasing"> </span>

There is something peculiar about lists (and other mutable data types) that we need to be careful about while
assigning them to variables. First, consider the following code:

**“The first example”**  

In [ ]:
print("address of 5: ", id(5))
a = 5
print("address of a: ", id(a))
b = a
print("address of b: ", id(b))
a = 3
print("address of a: ", id(a))
print("b is: ", b)

address of 5:  10869544
address of a:  10869544
address of b:  10869544
address of a:  10869480
b is:  5


Here, we used the `id()` function to display the addresses of the variables in the memory to help us understand what happened in those assignments:
  *  The second line creates `5` in the memory and links that with `a`. 
  *  The fourth line links the content of `a` with the variable `b`. Hereby, they
     are two different names for the same content. 
  *  The sixth line creates
     a new content, `3`, and assigns it to `a`. Now, `a` points to a
     different memory location than `b`. 
  * `b` still points to `5`,
     which is printed.

Now, let us keep the task the same but change the data from an integer to a list:

**“The second example”**

In [ ]:
a = [5,1,7]
b = a
print("addresses of a and b: ", id(a), id(b))
print("b is: ", b)
a = [3,-1]
print("addresses of a and b: ", id(a), id(b))
print("b is: ", b)


addresses of a and b:  4364549568 4364549568
b is:  [5, 1, 7]
addresses of a and b:  4364490688 4364549568
b is:  [5, 1, 7]



In other words, this works similarly to the first example, as expected.

In contrast, consider the following slightly different example:

**“The third example”**

In [ ]:
a = [5,1,7]
b = a
print("addresses of a and b: ", id(a), id(b))
print("b is: ", b)
a[0] = 3
print("addresses of a and b: ", id(a), id(b))
print("b is: ", b)

addresses of a and b:  140043083306048 140043083306048
b is:  [5, 1, 7]
addresses of a and b:  140043083306048 140043083306048
b is:  [3, 1, 7]



To our surprise, changing the first element of `a`(with `a[0] = 3`)  also
affected `b`. This should not be surprising since both `a` and
`b` point to the same memory location and since a list is mutable,
when we change an element in that memory location, it affects both `a`
and `b` since they are just different names for the same memory location.

This behavior is called *aliasing*.
Although the examples above used lists for illustration purposes,
aliasing pertains to all mutable data types.

Aliasing is a powerful concept that can be hazardous and beneficial
depending on the context:
  *  If you carelessly assign a mutable variable to another variable,
     changes made on one variable are going to affect on the other one. If this
     is not intended and the location in the code where the aliasing is
     initiated cannot be identified, you may lose hours or days trying
     to identify the source of the problem in your code.
  *  Aliasing can be beneficial, especially when we want changes made to one variable to be reflected in another. This will be useful for passing
     data to functions and getting the results of computations from functions.
     

### 4.4.3 Naming Variables
<span id="chapters_ch4_dive_into_python_naming_variables"> </span>

Programmers usually choose a name for a variable such that the name signifies what
the content will be. In Python, variable names may be arbitrarily long. They may
contain letters (from the English alphabet), as well as numbers and
underscores, but they must start with a letter or an underscore. While
using uppercase letters is allowed, bear in mind that programmers
reserve starting with an upper case to differentiate a property (i.e., *scope*)
of the variable which you will learn later (when we introduce
functions).

The following is a list of some valid variable names:
<table><tr><td>
<tt>y</tt>
<td>
<tt>y1</tt>
<td>
<tt>Y</tt>
<td>
<tt>Y_1</tt>
<td>
<tt>_1</tt>
<tr><td> 
<tt>temperature</tt>
<td>
<tt>temperature_today</tt>
<td>
<tt>TemperatureToday</tt>
<td>
<tt>Cumulative</tt>
<td>
<tt>coordinate_x</tt>
<tr><td> 
<tt>a1b145c</tt>
<td>
<tt>a_1_b1_45_c</tt>
<td>
<tt>s_s_</tt>
<td>
<tt>_</tt>
<td>
<tt>___</tt>
</td>
</table>

As you might have noticed, though they are perfectly valid, the five
examples in the last row may not be sensible as they do not provide any information about the content they store. 

When naming variables, you can consider the following guideline:
  *  It is a better practice to name variables that reflect the value they are going to store.
     For example:
     ```python
     >>> a = b * c
     ```
     is syntactically correct, but its purpose is not evident. Contrast this
     with:
     ```python
     >>> salary = hours_worked * hourly_pay_rate
     ```

     where the values stored by the variables are more clear, making the computation and the code easier to follow.
  *  You should use different variables for different data, which is named as the “<a href="https://en.wikipedia.org/wiki/Single-responsibility_principle">Single
     Responsibility Principle</a>“ in Computer Science. For example, even if you could use the
     same variable in one statement to count students and in another statement to hold the largest grade, this is not recommended. In programming, we do not
     economize with variables. Rather, we strive to make the code readable, and for this purpose, we introduce different variables, when necessary, to reflect the semantics and the context, uniquely.    
  *  Variable names should be pronounceable, making them easier to
     remember.     
  *  Avoid variable names that could misguide you or others looking
     at your code.     
  *  Use `i,j,k,m,n` only for counting: Programmers implicitly recognize
     such variables as holding integers (for historical reasons).     
  *  Use `x,y,z` for coordinate values or multi-variate function
     arguments.     
  *  Avoid the single character variable `l` as it can be easily
     confused with `1`(one).    
  *  If you are using multiple words as a variable name, choose one of
     the following:
  *  Make all words lowercase, combine them using `_` as separator;
          e.g., `highest_midterm_grade`,
     `shortest_path_distance_up_to_now`.          
  *  Capitalize the first letter of each word, except for the first, and combine all words directly without using a separator; e.g.,      `highestMidtermGrade`, `shortestPathDistanceUpToNow`.
          
**Reserved Names**  
The following keywords are being used by Python already and, therefore, cannot be used as variable names. It is possible to use the name of a built-in function as a variable name (e.g., `len = 20`). This, however, loses access to such a built-in function until the interpreter is restarted.

<table><tr><td>
and
<td>
def
<td>
exec
<td>
if
<td>
not
<td>
return

<tr><td> 

assert
<td>
del
<td>
finally
<td>
import
<td>
or
<td>
try

<tr><td> 

break
<td>
elif
<td>
for
<td>
in
<td>
pass
<td>
while

<tr><td> 

class
<td>
else
<td>
from
<td>
is
<td>
print
<td>
yield

<tr><td> 

continue
<td>
except
<td>
global
<td>
lambda
<td>
raise
<td>
</table>

### 4.4.4 Other Basic Statements
<span id="chapters_ch4_dive_into_python_other_basic_statements"> </span>

Python has other basic statements listed below:

`pass, del, return, yield, raise, break, continue, import, future, global, nonlocal`.

Among these, we have seen `del` and we will see some others in the
rest of the book.

`print` used to be a statement in Python version 2. However, this has changed, and `print` is a function in Python version 3. 
Therefore, `print` has a
value (which we will see later).



## 4.5 Compound Statements
<span id="chapters_ch4_dive_into_python_compound_statements"> </span>

Like other high-level languages, Python provides statements that combine
other statements as their parts. Two examples are:
  *  Conditional statements where different statements are executed based
     on the truth value of a condition, e.g.:
      
     ```python
     if <boolean-expression>:
         statement-true-1
         statement-true-2
         ...
     else:
        statement-false-1
        statement-false-2
        ...
     ```
  * Repetitive statements where some statements are executed more than
     once depending on a condition or for a fixed number of times, e.g.:
    ```python
     while <boolean-condition>:
         statement-true-1
         statement-true-2
         ...
    ```

    which executes the statements while the condition is true.

We will see these and other forms of compound statements in the rest of
the book.

## 4.6 Basic Actions for Interacting with the Environment
<span id="chapters_ch4_dive_into_python_basic_actions_for_interacting_with_the_environment"> </span>

In our programs, we frequently require obtaining some input from the
user or displaying some data to the user. For these purposes, we can use the following.

### 4.6.1 Actions for Input
<span id="chapters_ch4_dive_into_python_actions_for_input"> </span>

In Python, you can use the `input()` function to obtain input from
the user:
```python
input(<prompt>)
```

where `<prompt>` is an optional informative string displayed to the user before getting the input. The following is a simple example:
```python
>>> s = input("Now enter your text: ")
Now enter your text: This is the text I entered
>>> print(s)
This is the text I entered
```

The `input()` function gives the programmer a string.
If you expect the user to enter an expression, you can evaluate the expression in the string using
the `eval()` function as we explained in 
<a href="#chapters_ch4_dive_into_python_string">Section 4.2.3</a>.


### 4.6.2 Actions for Output
<span id="chapters_ch4_dive_into_python_actions_for_output"> </span>

To display data on the screen, Python provides the `print()`
function:
```python
print(item1, item2, ..., itemN)
```

For example:
```python
>>> print('Python', 'is', 'so', 'fun')
Python is so fun
```

In many cases, we end up with strings that have placeholders (marked with `int`) for data
items that we can fill in using a formatting function as follows:
```python
>>> print("I am {0} tall, {1} years old and have {2} eyes".format(1.86, 20, "brown"))
I am 1.86 tall, 20 years old, and have brown eyes
```

where the placeholder with the integer index $i$ is filled in with the parameter of the `format()` function at index $i$.

Alternatively, instead of using integers for the placeholders, we can
give them names or labels (as `label`):

```python
>>> print("I am {height} tall, {age} years old and have {eyes} eyes. Did I tell you that I was {age}?".format(age=20, eyes="brown", height=1.86))
I am 1.86 tall, 20 years old, and have brown eyes. Did I tell you that I was 20?
```

where a placeholder is filled in with the matching labeled parameter of the format function.

The `format()` function provides many more functionalities than the
ones we have illustrated. However, the use exemplified here should be sufficient for
general use and this book. The reader interested in complete coverage
is referred to [Python’s documentation on string
formatting](https://docs.python.org/3/library/string.html).

A more handy approach for printing is to tell Python (using `f"dots"`) to use existing variables to fill in the placeholders:
```python
>>> age = 20
>>> height = 1.70
>>> eye_color = "brown"
>>> print(f"I am {height} tall, {age} years old and have {eye_color} eyes")
I am 1.7 tall, 20 years old, and have brown eyes
```

Note that, in this example, the `format()` function is not used. Instead, Python directly used the variables defined before the `print()` function.

## 4.7 Actions That Are Ignored
<span id="chapters_ch4_dive_into_python_actions_that_are_ignored"> </span>

In Python, we have two actions that are ignored by the interpreter:

### 4.7.1 Comments
<span id="chapters_ch4_dive_into_python_comments"> </span>

Like other high-level languages, Python provides programmers with mechanisms
for writing comments in their programs:
  * **Comments with `#`**: When Python encounters the symbol `#` in your code, it
     assumes that the current line is finished, ignores the rest of the line, 
     evaluates and runs the current line and continues interpretation with
     the next line. For example:
     ```python
     >>> 3 + 4 # We are adding two numbers here
     7
    ```
  * **Multi-line comments with triple-quotes**: To provide
     comments longer than one line, you can use triple quotes:
     ```python
     """
     This is a multi-line comment.
     We are flexible with the number of lines &
       characters, and
         spacing. Python
           will ignore them.
     """
     ```

     Multi-line comments are generally used by programmers to write
     documentation-level explanations and descriptions for their codes. There
     are document-generation tools that process triple-quotes to
     automatically generate documents for codes.
     
As we have seen before, multi-line comments are actually strings
     in Python. Therefore, if you use triple-quotes to provide a comment,
     make sure that it does not overlap with an expression or a statement line in your code.

### 4.7.2 `pass` Statement
<span id="chapters_ch4_dive_into_python_pass_statements"> </span>

Python provides the `pass` statement that is ignored by the
interpreter. The `pass` statement is generally used in incomplete
function implementations or compound statements to place a dummy placeholder
(to be filled in later) so that the interpreter does not complain about missing a statement. For example:


```python
if <condition>:
      pass # @TODO fill this part
else:
      statement-1
      statement-2
      ...
```

## 4.8 Actions and Data Packaged in Libraries
<span id="chapters_ch4_dive_into_python_actions_and_data_packaged_in_libraries"> </span>

Python, like many high-level programming languages, provides a wide
spectrum of actions and data predefined and organized in “packages“ that
we call libraries. For example, there is a library for mathematical
functions and constant definitions which you can access using
`from math import *` as follows: 
```python
>>> pi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pi' is not defined
>>> sin(pi)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'sin' is not defined
>>> from math import *
>>> pi
3.141592653589793
>>> sin(pi)
1.2246467991473532e-16
```

Below is a short list of libraries that might be useful:


<table><tr><th> 
Library
<th> 
Description
<tr><td> 
math
<td>
Mathematical functions and definitions
<tr><td> 
cmath
<td>
Mathematical functions and definitions for complex numbers
<tr><td> 
fractions
<td>
Rational numbers and arithmetic
<tr><td> 
random
<td>
Random number generation
<tr><td> 
statistics
<td>
Statistical functions
<tr><td> 
os
<td>
Operating system functionalities
<tr><td> 
time
<td>
Time access and conversion functionalities
<tr><td> 
</table>

Of course, the list is too wide to practically cover and
explain here. The interested reader is directed to check
the comprehensive list at [Python
docs](https://docs.python.org/3/library/).

The `import` statement that we used above *loads* the library and makes
its contents directly accessible by directly using their names
(e.g., `sin(pi)`). Alternatively, we can do the following:


```python
>>> import math
>>> math.sin(math.pi)
1.2246467991473532e-16
```

which requires us to specify the name `math` every time we need to
access something from it. We could also change the name:


```python
>>> import math as m
>>> m.sin(m.pi)
1.2246467991473532e-16
```

However, we discourage this way of using libraries until  where
we introduce the concept of objects and object-oriented programming.

To find out what is available in a library or any data item, you can use the `dir()` function:
```python
>>> import math
>>> dir(math)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']
```

## 4.9 Providing Actions to the Interpreter
<span id="chapters_ch4_dive_into_python_providing_your_actions_to_the_interpreter"> </span>

Python provides different options to provide your actions and
get them executed.



### 4.9.1 Directly Interacting with the Interpreter
<span id="chapters_ch4_dive_into_python_directly_interacting_with_the_interpreter"> </span>

As we have seen until now, you can interact with and type our actions into the interpreter directly. When you are done with the
interpreter, you can finish the session and quit the interpreter using the functions `quit()` or `exit()` or by
pressing `CTRL-D`. For example:

```python
$ python3
Python 3.8.5 (default, Jul 21 2020, 10:48:26)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print("Python is fun")
Python is fun
>>> print("Now I am done")
Now I am done
>>> quit()
$
```

where we see that, after quitting the interpreter, we are back at the
terminal shell.

Although this way of coding is simple and very interactive, when your
code gets longer and more complicated, it makes it difficult to manage. 
Moreover, when you exit the interpreter, all your actions and executions are
lost, and to be able to run them again, you need to retype them from
scratch. This can be tedious, redundant, impractical, and inefficient.

### 4.9.2 Writing Actions in a File (Script)
<span id="chapters_ch4_dive_into_python_writing_actions_in_a_file_script"> </span>

Alternatively, you can place our actions in a file with the “`.py`” 
extension in the filename as follows:

```python
print("This is a Python program that reads two numbers from the user, adds the numbers and prints the result\n\n")
[a, b] = eval(input("Enter a list of two numbers as [a, b]: "))
print("You have provided: ", a, b)
result = a + b
print("The sum is: ", result)
```

Assuming you have saved these lines in a file (named `test.py`), you can execute the actions in a terminal shell by running the command “`python3 test.py`” 
(“`cat test.py`” only displays the content of the file):

```python
$ cat test.py
print("This is a Python program that reads two numbers from the user, adds the numbers, and prints the result\n\n")
[a, b] = eval(input("Enter a list of two numbers as [a, b]: "))
print("You have provided: ", a, b)
result = a + b
print("The sum is: ", result)
$ python3 test.py
This is a Python program that reads two numbers from the user, adds the numbers and prints the result

Enter a list of two numbers as [a, b]: [3, 4]
You have provided:  3 4
The sum is:  7
```

A more advanced feature is to provide *command-line arguments* to your script and use
the arguments provided in your script (named `test.py`):

```python
from sys import argv

print("The arguments of this script are:\n", argv)

exec(argv[1]) # Get a
exec(argv[2]) # Get b

print("The sum of a and b is: ", a+b)
```

which can be run as follows with the command-line arguments:

```python
$ python3 test.py a=10 b=20
The arguments of this script are:
 ['test.py', 'a=10', 'b=20']
The sum of a and b is:  30
```

Note that this example used the function `exec()`, which executes the
statement provided to the function as a string argument. Compare this
with the `eval()` function that we have introduced before: `eval()`
takes an expression, whereas `exec()` takes a statement.

### 4.9.3 Using Actions from Libraries (Modules)
<span id="chapters_ch4_dive_into_python_writing_your_actions_as_libraries_modules"> </span>

Another mechanism for executing your actions is to place them into
libraries (modules) and provide them to Python using the `import`
statement, as we have illustrated in <a href="#chapters_ch4_dive_into_python_actions_and_data_packaged_in_libraries">Section 4.8</a>. For example, if you
have a `test.py` file with the following content:

```python
a = 10
b = 8
sum = a + b
print("a + b with a =", a, " and b =", b, " is: ", sum)
```

In another Python script or in the interpreter, you can directly type:

```python
>>> from test import *
a + b with a = 10  and b = 8  is:  18
>>> a
10
>>> b
8
```

In other words, what you have defined in `test.py` becomes accessible
after being imported.

## 4.10 Important Concepts
<span id="chapters_ch4_dive_into_python_important_concepts"> </span>

We would like our readers to have grasped the following crucial concepts
and keywords from this chapter (all related to Python):
  *  Basic data types.   
  *  Basic operations and expression evaluation     
  *  Precedence and associativity.  
  *  Variables and how to name them.  
  *  Aliasing problem.  
  *  Container types.  
  *  Accessing elements of a container type (indexing, negative indexing,
     slicing).  
  *  Basic I/O.  
  * Commenting on your codes.   
  *  Using libraries.  

## 4.11 Further Reading
<span id="chapters_ch4_dive_into_python_further_reading"> </span>
  *  A detailed history of Python and its versions: https://en.wikipedia.org/wiki/History_of_Python.
  *  The concept of aliasing: http://en.wikipedia.org/wiki/Aliasing_%28computing%29Wikipedia_Aliasing.
     

## 4.12 Exercises
<span id="chapters_ch4_dive_into_python_exercises"> </span>

  1. The Euclidean distance between two points $(a, b)$ and $(c, d)$ is defined as: $\sqrt{(a - c)^2 +(b - d)^2}$.
     Write a Python code that reads $a,b,c,d$ from the user,
     calculates the Euclidean distance, and prints the result.

  1. To convert Celsius to Fahrenheit, we multiply Celsius by $9/5$ 
     and then add 32.  Write a Python code that reads a Celsius value and
     prints the equivalent Fahrenheit. 

  1. The formula for compound interest is the following:

      $$
      A = P\left(1 + \frac{r}{n}\right)^{n t}
      $$

      where:   
      - $A$ = final amount   
      - $P$ = initial principal value   
      - $r$ = annual interest rate   
      - $n$ = the number of times interest is applied per year   
      - $t$ = the number of years
  
     Write a Python code that reads $P,r,n,t$ from the user
     and prints $A$ as the result. 

  1. A sphere of radius $R_1$ is made of plastic. There is a sphere-shaped hole of radius $R_2$ $(R_2<R_1)$ in the plastic sphere.    
     Write a Python code that reads  $R_1, R_2$ from the user,
     and prints the volume of plastic used. 